# Generated by Django 5.0.3 on 2024-03-30 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_id',
            new_name='number',
        ),
        migrations.AddField(
            model_name='car',
            name='car_owner',
            field=models.ManyToManyField(through='project_first_app.Ownership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='owner',
            name='cars',
            field=models.ManyToManyField(through='project_first_app.Ownership', to='project_first_app.car'),
        ),
    ]
